#!/bin/sh
#
#    wpkg -- a windows packager
#    Copyright (C) 2006-2007  Made to Order Software Corporation
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#    Authors
#    Alexis Wilke   alexis@m2osw.com
#

PACKAGE=website.tar.bz2

# Refresh the docs
echo "sendweb: info: creating website"
dev/create_docs

# Create a tarball
echo "sendweb: info: compressing website"
mkdir -p tmp
cd doc
tar cjf ../tmp/$PACKAGE *

# Send the result to SF
cd ../tmp

echo "sendweb: info: sending website"
if scp $PACKAGE alexis_wilke@unigw.sourceforge.net:/home/groups/u/un/unigw/htdocs/$PACKAGE \
&& ssh alexis_wilke@unigw.sourceforge.net "cd /home/groups/u/un/unigw/htdocs/; tar -mxjf $PACKAGE; rm -rf $PACKAGE";
then
	# it worked
	echo "sendweb: info: web page successfully uploaded on SourceForge."
else
	echo "sendweb: error: could not install the web page files on SourceForge."
fi


