#!/bin/sh

if test -d sample2
then
	cd sample2
fi

# You can test with this line under MS-Windows the tar
# tool will include the .. in the path and wpkg will
# refuse to install it. (tar under Linux will remove
# the useless usr/../ part from the paths)
#tar --exclude='*.svn' -cjf data.tar.bz2 usr/../usr

tar --exclude='*.svn' -cjf data.tar.bz2 usr
md5sum -b >md5sums `find usr -type f`
tar czf control.tar.gz control md5sums preinst postinst prerm postrm
echo 2.0 >debian-binary
rm -f sample.deb
ar cqS sample.deb debian-binary control.tar.gz data.tar.bz2
